Fernmeldewesen - Einrichtungen
jonas-koeritz/Taktische-Zeichen pull request #117
Opened 2021-05-20 19:02 UTC by Daugl

Einsortierungen entweder in Fernmeldewesen oder unter Einrichtungen.

2021-05-21 14:27 UTC, jonas-koeritz commented
Kannst du hier noch die "viewbox" einfügen? (Gilt analog auch für die restlichen Zeichen wo es fehlt)

2021-05-23 11:41 UTC, Daugl commented
Viewbox für die Zeichen hier sind eingearbitet, Rest folgt gleich.

2021-07-06 08:08 UTC, jonas-koeritz requested changes
Hier würde Ich die Namen der Zeichen noch gerne angepasst haben. Die können alle ohne Bedeutungsverlust zusammengeschrieben werden.
Bei der Vermittlungsstelle kommt dann natürlich noch ein "s" dazu ;)

2021-07-06 17:49 UTC, Daugl commented
> 
> 
> Hier würde Ich die Namen der Zeichen noch gerne angepasst haben. Die können alle ohne Bedeutungsverlust zusammengeschrieben werden.
> Bei der Vermittlungsstelle kommt dann natürlich noch ein "s" dazu ;)

Bitte sehr :)

2022-03-20 17:03 UTC, closed without merging